export class Smartphone {
    constructor(
        public brand: string = '',
        public model: string = '',
        public network_technology: string = '',
        public twoG_bands: string = '',
        public threeG_bands: string = '',
        public fourG_bands: string = '',
        public network_speed: string = '',
        public GPRS: string = '',
        public EDGE: string = '',
        public announced: string = '',
        public status: string = '',
        public dimentions: string = '',
        public weight_g: string = '',
        public weight_oz: string = '',
        public SIM: string = '',
        public display_type: string = '',
        public display_resolution: string = '',
        public display_size: string = '',
        public OS: string = '',
        public CPU: string = '',
        public Chipset: string = '',
        public GPU: string = '',
        public memory_card: string = '',
        public internal_memory: string = '',
        public RAM: string = '',
        public primary_camera: string = '',
        public secondary_camera: string = '',
        public loud_speaker: string = '',
        public audio_jack: string = '',
        public WLAN: string = '',
        public bluetooth: string = '',
        public GPS: string = '',
        public NFC: string = '',
        public radio: string = '',
        public USB: string = '',
        public sensors: string = '',
        public battery: string = '',
        public colors: string = '',
        public approx_price_EUR: string = '',
        public img_url: string = ''
    ) { }
}